version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: ec2-54-235-92-244.compute-1.amazonaws.com
            database: dapnk1jmu8hnke
            schema: default
            user: ddtactvdrplgre
            password: c8f7239f480ad40d1f044d363722c5c33c4b3420ad7819000d7f7bf9ff0f342c
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
